cloud:
 aws:
  accessKeyId:
  region: 
  bucketname:
  secretKey:
 spring:
  application:
    name: 
    
    
 logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace
server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbms
    username: root
    password: ashok 
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

